name: Test Emscripten Installation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-emsdk:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      run: |
        git clone https://github.com/kazakiriGTT/keshi.git .
        git checkout main
      
    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
        emcc --version
        
    - name: Download Raylib for Web
      run: |
        curl -L https://github.com/raysan5d/raylib/releases/download/5.5/raylib-5.5_webASM.zip -o raylib-web.zip
        unzip raylib-web.zip -d raylib-web
        ls -la raylib-web